# Generated by Django 3.0 on 2019-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GaragNumb', models.IntegerField()),
                ('Marsh', models.IntegerField()),
                ('Graph', models.IntegerField()),
                ('Smena', models.IntegerField()),
                ('TimeNav', models.DateTimeField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Speed', models.IntegerField()),
                ('Azimuth', models.IntegerField()),
            ],
        ),
    ]
